name: Code Quality

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.json'
      - '**/*.yml'

jobs:
  eslint:
    name: Eslint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run Eslint
        run: npm run lint

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run Prettier Check
        run: npm run format:check

  build:
    name: Frontend Build Check
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build Frontend Application
        run: cd apps/web && npm run build
